apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: 5thcinema/go-backend-services:kubiya
        imagePullPolicy: Always
        ports:
        - containerPort:  5555

